# Generated by Django 5.0.4 on 2024-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='day_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
