# Generated by Django 5.0.4 on 2024-10-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
    ]
