# Generated by Django 5.0.4 on 2024-10-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_employee_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
