# Generated by Django 5.0.4 on 2024-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
