# Generated by Django 5.0.4 on 2024-10-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_field_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='home.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='home.employee')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assignments', to='home.field')),
            ],
            options={
                'unique_together': {('employee', 'field', 'department')},
            },
        ),
    ]
