# Generated by Django 5.0.4 on 2024-10-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_employeeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='home.department')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='home.field')),
            ],
            options={
                'unique_together': {('name', 'field', 'department')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeeAssignment',
        ),
    ]
