# Generated by Django 5.0.4 on 2024-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_employeeassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='notes',
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
