# Generated by Django 5.0.4 on 2024-10-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_assignments', to='home.employee'),
        ),
    ]
