# Generated by Django 5.0.4 on 2024-10-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_employeeassignment_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_groups', to='home.employee'),
        ),
    ]
