# Generated by Django 5.0.4 on 2024-10-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_employeeassignment_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
